version: '3'

networks:
  mongo-network: # 可修改确保下面的和这个同名的网络都被修改
    external: true
    name: 'mongo-network'
  redis-network: # 可修改确保下面的和这个同名的网络都被修改
    external: true
    name: 'redis'
  api-network: # 可修改确保下面的和这个同名的网络都被修改
    external: true
    name: 'api'

services:

  api:
    image: doconnor/movies-api:1.0
    container_name: movies-api
    environment:
      - MONGODB_URI=mongodb://admin:password@mongo:27017
      - REDIS_URI=redis://redis
      - ENABLE_WRITING_HANDLERS=false
    ports:
      - '9000:9000'
    networks:
      - api-network
      - redis-network
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:8.0-rc
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - mongo-network
      - api-network
    ports:
      - '27017:27017'
    volumes:
      - ./seed:/data/db

  mongo-express:
    image: mongo-express:1.0-20-alpine3.19
    container_name: express
    restart: always
    ports:
      - '8080:8081'
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongo
    networks:
      - mongo-network
    depends_on:
      - mongo

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - redis-network
